//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.DataService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataService.IWCFDataService")]
    public interface IWCFDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFDataService/Add", ReplyAction="http://tempuri.org/IWCFDataService/AddResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonLibrary.Employee))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonLibrary.Student))]
        void Add(CommonLibrary.ManagableElement element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFDataService/Add", ReplyAction="http://tempuri.org/IWCFDataService/AddResponse")]
        System.Threading.Tasks.Task AddAsync(CommonLibrary.ManagableElement element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFDataService/Edit", ReplyAction="http://tempuri.org/IWCFDataService/EditResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonLibrary.Employee))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonLibrary.Student))]
        void Edit(CommonLibrary.ManagableElement element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFDataService/Edit", ReplyAction="http://tempuri.org/IWCFDataService/EditResponse")]
        System.Threading.Tasks.Task EditAsync(CommonLibrary.ManagableElement element);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFDataServiceChannel : Client.DataService.IWCFDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFDataServiceClient : System.ServiceModel.ClientBase<Client.DataService.IWCFDataService>, Client.DataService.IWCFDataService {
        
        public WCFDataServiceClient() {
        }
        
        public WCFDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Add(CommonLibrary.ManagableElement element) {
            base.Channel.Add(element);
        }
        
        public System.Threading.Tasks.Task AddAsync(CommonLibrary.ManagableElement element) {
            return base.Channel.AddAsync(element);
        }
        
        public void Edit(CommonLibrary.ManagableElement element) {
            base.Channel.Edit(element);
        }
        
        public System.Threading.Tasks.Task EditAsync(CommonLibrary.ManagableElement element) {
            return base.Channel.EditAsync(element);
        }
    }
}
