// Type: System.Linq.Expressions.ExpressionType
// Assembly: System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// MVID: FF46A1FC-D9B9-4455-A224-A9DA86AA1C2B
// Assembly location: C:\Windows\Microsoft.NET\Framework\v4.0.30319\System.Core.dll

namespace System.Linq.Expressions
{
  [__DynamicallyInvokable]
  public enum ExpressionType
  {
    [__DynamicallyInvokable] Add,
    [__DynamicallyInvokable] AddChecked,
    [__DynamicallyInvokable] And,
    [__DynamicallyInvokable] AndAlso,
    [__DynamicallyInvokable] ArrayLength,
    [__DynamicallyInvokable] ArrayIndex,
    [__DynamicallyInvokable] Call,
    [__DynamicallyInvokable] Coalesce,
    [__DynamicallyInvokable] Conditional,
    [__DynamicallyInvokable] Constant,
    [__DynamicallyInvokable] Convert,
    [__DynamicallyInvokable] ConvertChecked,
    [__DynamicallyInvokable] Divide,
    [__DynamicallyInvokable] Equal,
    [__DynamicallyInvokable] ExclusiveOr,
    [__DynamicallyInvokable] GreaterThan,
    [__DynamicallyInvokable] GreaterThanOrEqual,
    [__DynamicallyInvokable] Invoke,
    [__DynamicallyInvokable] Lambda,
    [__DynamicallyInvokable] LeftShift,
    [__DynamicallyInvokable] LessThan,
    [__DynamicallyInvokable] LessThanOrEqual,
    [__DynamicallyInvokable] ListInit,
    [__DynamicallyInvokable] MemberAccess,
    [__DynamicallyInvokable] MemberInit,
    [__DynamicallyInvokable] Modulo,
    [__DynamicallyInvokable] Multiply,
    [__DynamicallyInvokable] MultiplyChecked,
    [__DynamicallyInvokable] Negate,
    [__DynamicallyInvokable] UnaryPlus,
    [__DynamicallyInvokable] NegateChecked,
    [__DynamicallyInvokable] New,
    [__DynamicallyInvokable] NewArrayInit,
    [__DynamicallyInvokable] NewArrayBounds,
    [__DynamicallyInvokable] Not,
    [__DynamicallyInvokable] NotEqual,
    [__DynamicallyInvokable] Or,
    [__DynamicallyInvokable] OrElse,
    [__DynamicallyInvokable] Parameter,
    [__DynamicallyInvokable] Power,
    [__DynamicallyInvokable] Quote,
    [__DynamicallyInvokable] RightShift,
    [__DynamicallyInvokable] Subtract,
    [__DynamicallyInvokable] SubtractChecked,
    [__DynamicallyInvokable] TypeAs,
    [__DynamicallyInvokable] TypeIs,
    [__DynamicallyInvokable] Assign,
    [__DynamicallyInvokable] Block,
    [__DynamicallyInvokable] DebugInfo,
    [__DynamicallyInvokable] Decrement,
    [__DynamicallyInvokable] Dynamic,
    [__DynamicallyInvokable] Default,
    [__DynamicallyInvokable] Extension,
    [__DynamicallyInvokable] Goto,
    [__DynamicallyInvokable] Increment,
    [__DynamicallyInvokable] Index,
    [__DynamicallyInvokable] Label,
    [__DynamicallyInvokable] RuntimeVariables,
    [__DynamicallyInvokable] Loop,
    [__DynamicallyInvokable] Switch,
    [__DynamicallyInvokable] Throw,
    [__DynamicallyInvokable] Try,
    [__DynamicallyInvokable] Unbox,
    [__DynamicallyInvokable] AddAssign,
    [__DynamicallyInvokable] AndAssign,
    [__DynamicallyInvokable] DivideAssign,
    [__DynamicallyInvokable] ExclusiveOrAssign,
    [__DynamicallyInvokable] LeftShiftAssign,
    [__DynamicallyInvokable] ModuloAssign,
    [__DynamicallyInvokable] MultiplyAssign,
    [__DynamicallyInvokable] OrAssign,
    [__DynamicallyInvokable] PowerAssign,
    [__DynamicallyInvokable] RightShiftAssign,
    [__DynamicallyInvokable] SubtractAssign,
    [__DynamicallyInvokable] AddAssignChecked,
    [__DynamicallyInvokable] MultiplyAssignChecked,
    [__DynamicallyInvokable] SubtractAssignChecked,
    [__DynamicallyInvokable] PreIncrementAssign,
    [__DynamicallyInvokable] PreDecrementAssign,
    [__DynamicallyInvokable] PostIncrementAssign,
    [__DynamicallyInvokable] PostDecrementAssign,
    [__DynamicallyInvokable] TypeEqual,
    [__DynamicallyInvokable] OnesComplement,
    [__DynamicallyInvokable] IsTrue,
    [__DynamicallyInvokable] IsFalse,
  }
}
